http:
  port: 80
server:
  port: 9000
  ssl:
    key-store: classpath:4870328_pxgandppm.top.pfx
    key-store-type: PKCS12
    key-store-password: WSRK1ksM
autoconfig:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.174.135:3306/empi
    username: root
    password: 123456
# logging.level.com.pxg.app.core.mapper.appmapper=debug
logging:
  level:
    empi:
      core:
        dao: debug